
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 29 02:52:51 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int CONST = 17;
  public static final int CHAR = 23;
  public static final int YIELD = 48;
  public static final int EQUALS = 45;
  public static final int GRTEQ = 38;
  public static final int GRT = 37;
  public static final int CASE = 32;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 31;
  public static final int MINUS = 41;
  public static final int LESS = 39;
  public static final int RPAREN = 7;
  public static final int AND = 46;
  public static final int DIFFER = 36;
  public static final int OR = 47;
  public static final int COMMA = 8;
  public static final int CLASS = 18;
  public static final int INC = 34;
  public static final int DIV = 43;
  public static final int PLUS = 11;
  public static final int LESSEQ = 40;
  public static final int IF = 21;
  public static final int DOT = 49;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int RETURN = 10;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 12;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 42;
  public static final int MOD = 44;
  public static final int NUMBER = 19;
  public static final int BREAK = 29;
  public static final int IDENT = 20;
  public static final int VOID = 13;
  public static final int SWITCH = 28;
  public static final int COLON = 16;
  public static final int LBRACE = 3;
  public static final int ELSE = 22;
  public static final int ENUM = 50;
  public static final int READ = 30;
  public static final int WHILE = 27;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 25;
  public static final int QUESTION = 51;
  public static final int DEC = 35;
  public static final int PRINT = 9;
  public static final int DO = 26;
}

